name: 'Images'
description: 'Build Docker image and push it to registry'
inputs:
  registry:
    description: 'Registry name with owner. For example, docker.io/library/'
    default: "docker.io/library/"
  image_name:
    description: 'Image name to build'
    default: false
  username:
    description: 'Repository user'
    default: false
  password:
    description: 'Repository password'
    default: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Install Docker
      run: |
        apt-get update
        apt-get install -y docker.io
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}                                   
    - name: Build and push
      run: |
        build.sh "${{ inputs.registry }}" "${{ inputs.image_name }}"
          